source(file.path("R", "survey_dsl.R"))
source(file.path("R", "survey_parser.R"))
source(file.path("R", "survey_yaml.R"))

parsed <- parse_yaml_survey(file.path("tests", "fixtures", "routing_fixture.yaml"))
stopifnot(length(parsed$questions) == 3L)
stopifnot(identical(parsed$questions[[2L]]$id, "Q2"))
stopifnot(length(parsed$questions[[2L]]$route_conditions) == 1L)
stopifnot(identical(parsed$questions[[2L]]$route_conditions[[1L]]$predicate, "Q1 == 1"))

compiled <- compile_yaml_survey(parsed, "routing_fixture")
audit <- audit_survey(compiled)
stopifnot(audit$ok, length(audit$reachable) == 5L)

q1 <- state_map(compiled)[["Q1"]]
stopifnot(length(q1$transitions) == 3L)
stopifnot(identical(q1$transitions[[1L]]$target, "Q2"))
stopifnot(identical(q1$transitions[[1L]]$when, "Q1 == 1"))
stopifnot(identical(q1$transitions[[2L]]$target, "Q3"))
stopifnot(identical(q1$transitions[[2L]]$when, "Q1 == 2"))
stopifnot(identical(q1$transitions[[3L]]$target, "end"))

first_path <- run_survey(compiled, list(Q1 = 1))
second_path <- run_survey(compiled, list(Q1 = 2))
stopifnot(identical(first_path$path, c("start", "Q1", "Q2")))
stopifnot(identical(second_path$path, c("start", "Q1", "Q3")))

diagram <- mermaid_state_machine(compiled)
stopifnot(grepl("Q1 = 1", diagram, fixed = TRUE))
stopifnot(grepl("Q1 = 2", diagram, fixed = TRUE))
stopifnot(length(grep("Q1 = 1", diagram, fixed = TRUE)) == 1L)
dependencies <- dependency_edges(compiled)
stopifnot(nrow(dependencies) == 2L)
stopifnot(all(dependencies$source == "Q1"))
dependency_diagram <- mermaid_variable_dependencies(compiled)
stopifnot(grepl("flowchart LR", dependency_diagram, fixed = TRUE))
stopifnot(grepl("Q1 = 1", dependency_diagram, fixed = TRUE))
stopifnot(!grepl("Q2.*Q2", dependency_diagram))
stopifnot(!grepl("Q1 = 1 (", dependency_diagram, fixed = TRUE))
cat("YAML routing tests passed\n")