source(file.path("R", "survey_dsl.R"))
source(file.path("R", "survey_parser.R"))
source(file.path("R", "survey_yaml.R"))

parsed <- parse_yaml_survey(file.path("tests", "fixtures", "routing_fixture.yaml"))
stopifnot(length(parsed$questions) == 3L)
stopifnot(identical(parsed$questions[[2L]]$id, "Q2"))
stopifnot(length(parsed$questions[[2L]]$route_conditions) == 1L)
stopifnot(identical(parsed$questions[[2L]]$route_conditions[[1L]]$predicate, "Q1 == 1"))

compiled <- compile_yaml_survey(parsed, "routing_fixture")
audit <- audit_survey(compiled)
stopifnot(audit$ok, length(audit$reachable) == 5L)

q1 <- state_map(compiled)[["Q1"]]
stopifnot(length(q1$transitions) == 3L)
stopifnot(identical(q1$transitions[[1L]]$target, "Q2"))
stopifnot(identical(q1$transitions[[1L]]$when, "Q1 == 1"))
stopifnot(identical(q1$transitions[[2L]]$target, "Q3"))
stopifnot(identical(q1$transitions[[2L]]$when, "Q1 == 2"))
stopifnot(identical(q1$transitions[[3L]]$target, "end"))

first_path <- run_survey(compiled, list(Q1 = 1))
second_path <- run_survey(compiled, list(Q1 = 2))
stopifnot(identical(first_path$path, c("start", "Q1", "Q2")))
stopifnot(identical(second_path$path, c("start", "Q1", "Q3")))

diagram <- mermaid_state_machine(compiled)
stopifnot(grepl("Q1 = 1", diagram, fixed = TRUE))
stopifnot(grepl("Q1 = 2", diagram, fixed = TRUE))
stopifnot(length(grep("Q1 = 1", diagram, fixed = TRUE)) == 1L)
dependencies <- dependency_edges(compiled)
stopifnot(nrow(dependencies) == 2L)
stopifnot(all(dependencies$source == "Q1"))
dependency_diagram <- mermaid_variable_dependencies(compiled)
stopifnot(grepl("flowchart LR", dependency_diagram, fixed = TRUE))
stopifnot(grepl("Q1 = 1", dependency_diagram, fixed = TRUE))
stopifnot(!grepl("Q2.*Q2", dependency_diagram))
stopifnot(!grepl("Q1 = 1 (", dependency_diagram, fixed = TRUE))
pages <- dependency_page_plan(compiled, page_size = 2L)
stopifnot(length(pages$pages) == 2L)
page_one <- mermaid_variable_dependency_page(compiled, "page_1", pages)
page_two <- mermaid_variable_dependency_page(compiled, "page_2", pages)
stopifnot(grepl("go to page_2", page_one, fixed = TRUE))
stopifnot(grepl("from page_1", page_two, fixed = TRUE))
page_output <- write_multipage_dependency_diagram(compiled, tempfile(), "routing_fixture", page_size = 2L)
stopifnot(file.exists(file.path(page_output$directory, "page_1.mmd")))
stopifnot(file.exists(file.path(page_output$directory, "index.txt")))
pdf_output <- tempfile(fileext = ".pdf")
write_dependency_pdf(compiled, pdf_output, page_size = 2L)
stopifnot(file.exists(pdf_output), file.info(pdf_output)$size > 0)
custom_plan <- dependency_page_plan(compiled, page_count = 3L)
stopifnot(length(custom_plan$pages) == 3L)
custom_page <- mermaid_variable_dependency_page(compiled, "page_1", custom_plan, font_size = 16L)
stopifnot(grepl("fontSize.*16px", custom_page))
custom_suite <- write_dependency_suite(compiled, tempfile(), "routing_fixture", page_count = 3L,
	mermaid_font_size = 16L, pdf_font_size = 0.7)
stopifnot(custom_suite$page_count == 3L)
cat("YAML routing tests passed\n")