%%{init: {'themeVariables': {'fontSize': '14px'}}}%%
flowchart LR
  %% Page 1 of 20
  v1["Benefits74: Saving Attitudes and Behaviour89"]
  v2["Retirement89: Attitudes to saving for retirement89"]
  v3["ISAs131: National Savings & Investments134"]
  v4["Insurances142: Currency & Cash145"]
  v5["Cryptocurrency147: Other financial assets148"]
  v6["Loans172: Household Bills179"]
  v7["Bankruptcy180: Other income exc. Earnings and Benefits 181"]
  v8["Inheritance197: Inheritances received197"]
  v9["Trusts209: Questions for settlers who have put their own assets into a trust 209"]
  v10["Health215: Status of parents217"]
  v11["Ten1: How do you own or rent first line of address ?"]
  v12["StartDat: ENTER DATE INTERVIEW WITH THIS HOUSEHOLD WAS STARTED"]
  v13["DateChk: IS THIS:"]
  v14["IntrType: ENTER WHETHER A TELEPHONE OR FACE TO FACE INTERVIEW"]
  v15["CurStat: RName or KITE Name"]
  v16["MovedWth: Did this person move to the same new address/household as another person already coded?"]
  v17["CountRes: ENTER COUNTRY WHERE NOW RESIDENT"]
  v18["KnowDet: Which details are known of where this person has moved?"]
  v19["Add1: What is the first line of the new address, please include the house number or name, and the name of the street or road?"]
  v20["Add2: What is the second line of the new address?"]
  v21["Add3: If Add2 = Response - entered a second line of address"]
  v22["Add4: If Add3 = Response - entered a third line of address"]
  v23["PstTwn: And in which town is the new address?"]
  v24["PostCd: If you know it, what is the postcode for this new address?"]
  v25["SurePstC: CODE FOR CERTAINTY OF CORRECT POSTCODE"]
  v26["TeleNumb: PLEASE ENTER TELEPHONE NUMBER, INCLUDING STD CODE"]
  v27["EmailAdd: PLEASE ENTER EMAIL ADDRESS"]
  v28["HldStat: Derived:"]
  v29["SurNme: Ask if RSurNme OR KITE RSurname = empty - i.e. if new cohort"]
  v30["CorrNam: IS THIS NAME CORRECT?"]
  v31["UpdatNam: Can I have the correct full name please?"]
  v32["MoreNme: Is there anyone else who classes this residence as their main residence?"]
  v33["DteofBth: What is your date of birth?"]
  v34["June15: Is the 15th of June the actual date or an estimate?"]
  v35["AgeIf: What was your age last birthday?"]
  v36["DVage: Derived"]
  v37["xMarSta: What is your legal marital status?"]
  v38["MarChk: Is your husband /wife / civil partner a member of the household?"]
  v39["LivWth12: May I just check, are you living with someone in this household as a couple?"]
  v40["FtEd: Are you presently in full-time education?"]
  v41["FtEd19: Are you presently in full-time education?"]
  v42["QualChk: Which of the following best describes the qualification that you are currently working towards? Is it ..."]
  v43["HiHNum: You have told me that the following people jointly own or rent the accommodation. Who has the highest income from earnings, benefits, pensions and any other sources?"]
  v44["JntEldA: ENTER PERSON NUMBER OF THE ELDEST JOINT HOUSEHOLDER FROM THOSE WITH THE SAME HIGHEST INCOME:"]
  v15 -.->|CurStat = 3,4,5 - respondent moved| v16
  v15 -->|CurStat = 8 - respondent now resident abroad| v17
  v15 -.->|CurStat = 3,4 - a member of the household has moved within GB and details are known| v18
  v18 -.->|KnowDet = 1- address of mover known| v19
  v18 -.->|KnowDet = 1- address of mover known| v20
  v20 -->|Add2 = Response - entered a second line of address| v21
  v21 -->|Add3 = Response - entered a third line of address| v22
  v18 -->|KnowDet = 1 - address of mover known| v22
  v18 -->|KnowDet = 1 - address of mover known| v23
  v18 -->|KnowDet = 1 - address of mover known| v24
  v18 -->|KnowDet = 1 - address of mover known| v25
  v18 -->|KnowDet = 2 - telephone number of mover known| v26
  v18 -->|KnowDet = 3 - email address of mover known| v27
  v15 -.->|Curstat = 2, HldStat = 1| v28
  v30 -->|CorrNam = 2 - respondent’s name is incorrect| v31
  v33 -->|DteofBth = 15.06| v34
  v33 -.->|DteofBth = DK/RF does not know OR refuse date of birth| v35
  v36 -->|DVAge>=16 respondent is aged 16 or over| v37
  v37 -.->|XMARSTA = 2,6 respondent is married and living with husband/wife or in a legally recognised Civil Partnership| v38
  v36 -.->|DVAge >= 16 AND MarSta <> 2,6 more than 1 person in household and respondent is aged 16 or over and not married and living with husband/wife or in a legally recognised Civil Partnership| v39
  v36 -.->|DVAge>3 AND <19 - aged over 3 and under 19 years| v40
  v36 -->|DVAge = 19 - respondent is 19 years old| v41
  v40 -->|FtEd = 1 - in full time education| v42
  v43 -->|HiHNum = 17 - two or more joint householders have the same income| v44
  route25_to_page_2["route25 -> go to page_2"]
  v43 -.->|route25| route25_to_page_2
  route29_to_page_2["route29 -> go to page_2"]
  v36 -.->|route29| route29_to_page_2
  route33_to_page_2["route33 -> go to page_2"]
  v36 -.->|route33| route33_to_page_2
  route37_to_page_2["route37 -> go to page_2"]
  v11 -.->|route37| route37_to_page_2
  route38_to_page_2["route38 -> go to page_2"]
  v11 -.->|route38| route38_to_page_2
  route42_to_page_2["route42 -> go to page_2"]
  v28 -.->|route42| route42_to_page_2
  route43_to_page_2["route43 -> go to page_2"]
  v11 -.->|route43| route43_to_page_2
  route47_to_page_2["route47 -> go to page_2"]
  v11 -.->|route47| route47_to_page_2
  route48_to_page_2["route48 -> go to page_2"]
  v11 -.->|route48| route48_to_page_2
  route53_to_page_2["route53 -> go to page_2"]
  v11 -.->|route53| route53_to_page_2
  route55_to_page_2["route55 -> go to page_2"]
  v11 -.->|route55| route55_to_page_2
  route118_to_page_4["route118 -> go to page_4"]
  v36 -.->|route118| route118_to_page_4
  route119_to_page_4["route119 -> go to page_4"]
  v14 -.->|route119| route119_to_page_4
  route121_to_page_4["route121 -> go to page_4"]
  v36 -.->|route121| route121_to_page_4
  route122_to_page_4["route122 -> go to page_4"]
  v14 -.->|route122| route122_to_page_4
  route162_to_page_5["route162 -> go to page_5"]
  v36 -.->|route162| route162_to_page_5
  route167_to_page_5["route167 -> go to page_5"]
  v40 -.->|route167| route167_to_page_5
  route168_to_page_5["route168 -> go to page_5"]
  v40 -.->|route168| route168_to_page_5
  route169_to_page_5["route169 -> go to page_5"]
  v36 -.->|route169| route169_to_page_5
  route269_to_page_8["route269 -> go to page_8"]
  v36 -.->|route269| route269_to_page_8
  route272_to_page_8["route272 -> go to page_8"]
  v36 -.->|route272| route272_to_page_8
  route275_to_page_8["route275 -> go to page_8"]
  v36 -.->|route275| route275_to_page_8
  route278_to_page_8["route278 -> go to page_8"]
  v36 -.->|route278| route278_to_page_8
  route281_to_page_8["route281 -> go to page_8"]
  v36 -.->|route281| route281_to_page_8
  route284_to_page_8["route284 -> go to page_8"]
  v36 -.->|route284| route284_to_page_8
  route545_to_page_11["route545 -> go to page_11"]
  v36 -.->|route545| route545_to_page_11
  route546_to_page_11["route546 -> go to page_11"]
  v33 -.->|route546| route546_to_page_11
  route551_to_page_11["route551 -> go to page_11"]
  v39 -.->|route551| route551_to_page_11
  route552_to_page_11["route552 -> go to page_11"]
  v37 -.->|route552| route552_to_page_11
  route574_to_page_11["route574 -> go to page_11"]
  v39 -.->|route574| route574_to_page_11
  route575_to_page_11["route575 -> go to page_11"]
  v37 -.->|route575| route575_to_page_11
  route734_to_page_15["route734 -> go to page_15"]
  v11 -.->|route734| route734_to_page_15
